server:
  port: 8080
spring:
  application:
    name: "auth_services"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
routes:
  paths:
    users: "/api/v1/createUsers"
    findByEmail: "/api/v1/users/by-email"
adapters:
  r2dbc:
    host: "localhost"
    port: 5432
    database: "crediya_db"
    schema: "public"
    username: "postgres"
    password: "0123456"
flyway:
  enabled: true
  url: jdbc:postgresql://localhost:5432/crediya_db
  user: postgres
  password: 0123456
  locations: classpath:db/migration